### ISSUE TITLE
Help to execute the EW.py code 

### ISSUE THREAD

**Issue by MeArpanGhosh** [CoolStarsCU/PHEW#23]
Please tell me the correct way to input my spectrum FITS file with the other necessary input parameters that are required by the code  EW.py code of your PHEW (PytHon Equivalent Widths).

**Comment by alejocosmico** [comment]
Hi, the spectrum format that works best with PHEW.EW() is to have your spectrum data loaded as an array with wavelength, flux, and optional flux error as columns. For instance, you can make a list with two 1d numpy arrays: wavelength as a 1d numpy array and flux as a 1d numpy array. Try using the function read_spec() in the module readspec.py to see if it works with your fits files.

For the rest of the inputs, please refer to section 4.2 of the user guide, and let us know if you have specific questions about those.

**Comment by MeArpanGhosh** [comment]
Hi, Thanks for helping me out. I have now managed to run the code. Actually, the issue was with my FITS file. As you suggested, instead of loading my FITS file, I loaded my spectrum data as a list containing three 1d numpy arrays of wavelength, flux and error, following which PHEW.EW() worked.
